"""Write version_info.txt (a PyInstaller --version-file) from version.json, so
the exe's Windows file properties show the product name and version.

Usage: python tools/make_version_info.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_NAME = "Kamen SSHFS Manager"
AUTHOR = "Irnes Karaduz"

info = json.loads((ROOT / "version.json").read_text(encoding="utf-8"))
version = info["version"]
parts = [int(p) for p in version.split(".")] + [0] * 4
nums = tuple(parts[:4])
year = info.get("released", "")[:4] or "2026"

(ROOT / "version_info.txt").write_text(f"""# Generated by tools/make_version_info.py — do not edit
VSVersionInfo(
  ffi=FixedFileInfo(filevers={nums}, prodvers={nums}, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', '{AUTHOR}'),
      StringStruct('FileDescription', '{APP_NAME}'),
      StringStruct('FileVersion', '{version}'),
      StringStruct('InternalName', '{APP_NAME}'),
      StringStruct('LegalCopyright', 'Copyright (c) {year} {AUTHOR}. MIT License.'),
      StringStruct('OriginalFilename', '{APP_NAME}.exe'),
      StringStruct('ProductName', '{APP_NAME}'),
      StringStruct('ProductVersion', '{version}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""", encoding="utf-8")
print(f"version_info.txt written for {APP_NAME} {version}")
